[phases.setup]
nixPkgs = ["nodejs"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["npx prisma generate", "npm run build", "npx swc prisma/seed.ts -o dist/seed.js"]

[start]
cmd = "npx prisma db push && node dist/seed.js && node dist/main"
